---
apiVersion: v1
kind: Endpoints
metadata:
  name: duplicati
  namespace: traefik
subsets:
  - addresses:
      - ip: 10.30.0.30
    ports:
      - port: 8200
        name: http
        protocol: TCP
