---
apiVersion: v1
kind: Endpoints
metadata:
  name: nextcloud
  namespace: traefik
subsets:
  - addresses:
      - ip: 10.30.0.30
    ports:
      - port: 8008
        name: http
        protocol: TCP
