---
apiVersion: v1
kind: Endpoints
metadata:
  name: opnsense
  namespace: traefik
subsets:
  - addresses:
      - ip: 10.10.0.1
    ports:
      - port: 443
        name: https
        protocol: TCP
