---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox
  namespace: traefik
subsets:
  - addresses:
      - ip: 10.10.0.4
    ports:
      - port: 8006
        name: https
        protocol: TCP
