---
apiVersion: v1
kind: Endpoints
metadata:
  name: semaphore
  namespace: traefik
subsets:
  - addresses:
      - ip: 10.40.0.12
    ports:
      - port: 3000
        name: http
        protocol: TCP
