---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: domain-watchdog

helmCharts:
  - name: domain-watchdog
    repo: oci://registry.example.com/example-org/helm-charts
    version: 1.0.0
    releaseName: domain-watchdog
    namespace: domain-watchdog
    valuesFile: values.yaml

resources:
  - ingress
  - secrets
