---
apiVersion: v1
kind: Service
metadata:
  name: adguard-1
  namespace: traefik
spec:
  clusterIP: None
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-2
  namespace: traefik
spec:
  clusterIP: None
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
