---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: traefik
spec:
  clusterIP: None
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
    - port: 2424
      targetPort: 2424
      name: ssh
      protocol: TCP
    - port: 5050
      targetPort: 5050
      name: registry
      protocol: TCP
    - port: 8090
      targetPort: 8090
      name: pages
      protocol: TCP
