---
apiVersion: batch/v1
kind: Job
metadata:
  name: longhorn-post-upgrade
  namespace: longhorn-system
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: Exists
      containers:
        - name: longhorn-post-upgrade
