---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: hermes
  namespace: traefik
  labels:
    kubernetes.io/service-name: hermes
addressType: IPv4
endpoints:
  - addresses:
      - 10.10.0.17
    conditions:
      ready: true
ports:
  - port: 9119
    name: http
    protocol: TCP
