---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare-ddns

helmCharts:
  - name: cloudflare-ddns
    repo: oci://registry.example.com/example-org/helm-charts
    version: 1.0.1
    releaseName: cloudflare-ddns
    namespace: cloudflare-ddns
    valuesFile: values.yaml

resources:
  - secrets
