---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: cluster-issuer
    app.kubernetes.io/part-of: infrastructure
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@example.com
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
      - dns01:
          cloudflare:
            email: cloudflare@example.de
            apiTokenSecretRef:
              name: cloudflare-api-secret
              key: api-token
        selector:
          dnsZones:
            - "example.com"
