---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: snapotter

helmCharts:
  - name: snapotter
    repo: oci://registry.example.com/example-org/helm-charts
    version: 1.0.1
    releaseName: snapotter
    namespace: snapotter
    valuesFile: values.yaml

resources:
  - ingress
  - secrets
