---
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-database
  namespace: postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: delete-database
          image: bitnami/postgresql:18.1.0
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: postgres-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: gitea-db-secret
                  key: database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: gitea-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitea-db-secret
                  key: password
            - name: POSTGRESQL_HOST
              value: "postgresql"
            - name: POSTGRESQL_PORT
              value: "5432"
          command:
            - /bin/bash
            - -c
            - |
              # Enhanced waiting with timeout
              echo "Waiting for PostgreSQL at $POSTGRESQL_HOST:$POSTGRESQL_PORT..."
              timeout=300  # 5 minutes timeout
              elapsed=0

              until pg_isready -h "$POSTGRESQL_HOST" -p "$POSTGRESQL_PORT" -U postgres; do
                if [ $elapsed -ge $timeout ]; then
                  echo "Timeout waiting for PostgreSQL after ${timeout} seconds"
                  exit 1
                fi
                echo "PostgreSQL not ready yet... waiting ($elapsed/${timeout}s)"
                sleep 5
                elapsed=$((elapsed + 5))
              done

              echo "PostgreSQL is ready! Deleting database '$DB_NAME' and user '$DB_USER'..."

              # Terminate active connections to the database before deletion
              echo "Terminating active connections to database '$DB_NAME'..."
              psql -h "$POSTGRESQL_HOST" -p "$POSTGRESQL_PORT" -U postgres -c "
                SELECT pg_terminate_backend(pid)
                FROM pg_stat_activity
                WHERE datname = '$DB_NAME' AND pid <> pg_backend_pid();"

              # Drop database if it exists
              if psql -h "$POSTGRESQL_HOST" -p "$POSTGRESQL_PORT" -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = '$DB_NAME'" | grep -q 1; then
                echo "Dropping database '$DB_NAME'..."
                psql -h "$POSTGRESQL_HOST" -p "$POSTGRESQL_PORT" -U postgres -c "DROP DATABASE $DB_NAME;"
                echo "Database '$DB_NAME' deleted successfully"
              else
                echo "Database '$DB_NAME' does not exist, skipping..."
              fi

              # Drop user if it exists
              if psql -h "$POSTGRESQL_HOST" -p "$POSTGRESQL_PORT" -U postgres -tc "SELECT 1 FROM pg_user WHERE usename = '$DB_USER'" | grep -q 1; then
                echo "Dropping user '$DB_USER'..."
                psql -h "$POSTGRESQL_HOST" -p "$POSTGRESQL_PORT" -U postgres -c "DROP USER $DB_USER;"
                echo "User '$DB_USER' deleted successfully"
              else
                echo "User '$DB_USER' does not exist, skipping..."
              fi

              echo "Database '$DB_NAME' and user '$DB_USER' cleanup completed successfully!"
