---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bitwarden-ingressroute
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`bitwarden.example.com`)
      services:
        - kind: Service
          name: bitwarden
          port: 8080
          scheme: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bitwarden-smtp-ingressroute
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`smtp4dev.example.com`)
      services:
        - kind: Service
          name: bitwarden-smtp
          port: 5000
          scheme: http
