---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: technitium-1-ingressroute
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`dns1.example.com`)
      services:
        - kind: Service
          name: technitium-1
          port: 5380
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: technitium-2-ingressroute
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`dns2.example.com`)
      services:
        - kind: Service
          name: technitium-2
          port: 5380
