---
apiVersion: v1
kind: Service
metadata:
  name: technitium-1
  namespace: traefik
spec:
  clusterIP: None
  ports:
    - port: 5380
      targetPort: 5380
      name: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: technitium-2
  namespace: traefik
spec:
  clusterIP: None
  ports:
    - port: 5380
      targetPort: 5380
      name: http
      protocol: TCP
